apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbinit
  name: dbinit
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mysql:5.7
    generation: null
    importPolicy: {}
    name: "5.7"
status:
  dockerImageRepository: ""
